from django.conf.urls import patterns, url


urlpatterns = patterns('forum.views',
    url(r'^categories/$',
        'category_list',
        name='forum-category-list'),

    url(r'^$',
        'topic_list',
        name='forum-topic-list'),
    url(r'^topic/unread/$',
        'topic_unread',
        name='forum-topic-unread'),
    url(r'^topic/all-read/$',
        'topic_mark_all_read',
        name='forum-topic-mark-all-read'),
    url(r'^topic/create/$',
        'topic_create',
        name='forum-topic-create'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?delete/$',
        'topic_delete',
        name='forum-topic-delete'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?close/toggle/$',
        'topic_toggle_close',
        name='forum-topic-toggle-close'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?sticky/toggle/$',
        'topic_toggle_sticky',
        name='forum-topic-toggle-sticky'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?response/$',
        'post_create',
        name='forum-post-create'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?redirect-to/solving/$',
        'topic_redirect_to_solving_post',
        name='forum-topic-redirect-to-solving-post'),
    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?details/$',
        'topic_details',
        name='forum-topic-details'),

    url(r'^topic/(?P<topic_id>\d+)/(?:(?P<slug>[^/]+)/)?(?P<post_id>\d+)/is_solving/$',
        'post_is_solving',
        name='forum-post-is-solving'),

    url(r'^user/([^/]+)/$',
        'user_details',
        name='forum-user-details'),
    url(r'^user/([^/]+)/edit/$',
        'user_edit',
        name='forum-user-edit'),

    url(r'^user/menu/position/toggle/$',
        'user_menu_position_toggle',
        name='forum-user-menu-position-toggle'),
)
